# Generated by Django 5.2.5 on 2025-08-14 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('action', 'Acción'), ('adventure', 'Aventura'), ('rpg', 'RPG'), ('shooter', 'Shooter'), ('sports', 'Deportes')], max_length=50)),
                ('release_year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('game_material_type', models.CharField(choices=[('digital', 'Digital'), ('fisico', 'Físico')], max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('minimum_time', models.PositiveIntegerField(help_text='Tiempo mínimo (minutos) para alquilar / jugar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('initial_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('current_stock', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('state', models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'No disponible')], max_length=50)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_measurement', models.CharField(choices=[('unidad', 'Unidad'), ('min', 'Minutos')], max_length=100)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ConsoleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_date', models.DateField(auto_now_add=True)),
                ('maintenance_reason', models.CharField(choices=[('reparación', 'Reparación'), ('limpieza', 'Limpieza')], max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('responsible', models.CharField(blank=True, max_length=255, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_console', to='gamecenter.consoletype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('is_client', models.BooleanField(default=False)),
                ('client_type', models.CharField(blank=True, choices=[('regular', 'Regular'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningSalesBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('closing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_sales_box', to='gamecenter.person')),
                ('sales_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_sales_box', to='gamecenter.salesbox')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsoleReservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_date', models.DateField(auto_now_add=True)),
                ('hour_count', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_hour', models.DateTimeField(blank=True, null=True)),
                ('end_hour', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('reservado', 'Reservado'), ('cancelado', 'Cancelado')], default='reservado', max_length=50)),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lots', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_lots', to='gamecenter.lots')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_client', to='gamecenter.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lots',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lots_price', to='gamecenter.price'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category', to='gamecenter.category')),
                ('console_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_console_type', to='gamecenter.consoletype')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='lots',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots_product', to='gamecenter.product'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hour_count', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('session_date', models.DateField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('state', models.CharField(choices=[('en curso', 'En curso'), ('finalizado', 'Finalizado')], default='en curso', max_length=50)),
                ('lots', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_lots', to='gamecenter.lots')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_sale', models.DateField(auto_now_add=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('igv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=50, null=True)),
                ('state', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_client', to='gamecenter.person')),
                ('opening_sales_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='gamecenter.openingsalesbox')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_user', to='gamecenter.person')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_session', to='gamecenter.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsoleTypeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('console_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_games', to='gamecenter.consoletype')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_types', to='gamecenter.game')),
            ],
            options={
                'unique_together': {('console_type', 'game')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lots',
            unique_together={('product', 'lot_number')},
        ),
    ]
